from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from app.schemas.system import ExecutionStage, GeoMetadata

class DetectionItem(BaseModel):
    id: int
    label: str
    confidence: float
    bbox: List[float]  # [x1, y1, x2, y2]
    area_pixels: int
    area_percentage: float = 0.0

class DetectedRegion(BaseModel):
    id: int
    label: str
    confidence: float
    confidence_type: str = "model"  # LAE-DINO raw logit / sigmoid score
    bounding_box: List[float]  # [x1, y1, x2, y2] in pixel coords
    normalized_box: List[float]  # [ymin, xmin, ymax, xmax] 0-1
    area_pixels: int
    area_sq_meters: Optional[float] = None
    mask_polygon: Optional[List[List[int]]] = None  # polygon vertices [[x,y],...]
    segmentation_confidence: Optional[float] = None

class HighlightRequest(BaseModel):
    image_path: str = Field(..., description="Path to satellite image")
    prompt: str = Field(..., description="Target object prompt (e.g., 'building', 'road', 'water body', 'vehicle')")
    box_threshold: float = Field(0.25, ge=0.05, le=0.95, description="LAE-DINO box detection threshold")
    text_threshold: float = Field(0.25, ge=0.05, le=0.95, description="LAE-DINO text matching threshold")
    use_mask2former_refinement: bool = Field(True, description="Refine boxes into accurate polygon masks via Mask2Former")
    use_sam2_refinement: Optional[bool] = Field(None, description="Legacy alias for use_mask2former_refinement")
    semantic_model: Optional[str] = Field("geochat", description="Semantic explanation model: 'geochat'")

class HighlightResponse(BaseModel):
    task: str = "image_highlight"
    status: str = "success"
    prompt: str
    num_detections: int
    detections: List[DetectedRegion]
    total_highlighted_area_pixels: int
    total_area_percentage: float
    annotated_image_url: str
    mask_image_url: str
    original_image_url: str
    model: str = "LAE-DINO + Mask2Former"
    detection_model: str = "LAE-DINO"
    segmentation_model: str = "Mask2Former"
    semantic_model: str = "GeoChat"
    device: str = "cuda"
    processing_time_ms: float
    specialized_time_ms: Optional[float] = None
    semantic_time_ms: Optional[float] = None
    geo_metadata: Optional[GeoMetadata] = None
    execution_trace: List[ExecutionStage] = []
    semantic_summary: Optional[str] = None
    transparency_warning: Optional[str] = (
        "Visual bounding boxes and segmentation masks are computed exclusively by LAE-DINO and Mask2Former. "
        "Semantic summary is generated by GeoChat + Gemini."
    )
